export const CONTACT_FORM_FIELDS = [
  {
    rowId: 1,
    cols: [
      {
        colId: 1,
        md: 6,
        name: "name",
        label: "Nombre",
        type: "text",
        required: true,
        pattern: undefined,
        minLength: 3,
        maxLength: 20,
        feedback: "Por favor, ingresa tu nombre.",
      },
      {
        colId: 2,
        md: 6,
        name: "surname",
        label: "Apellido",
        type: "text",
        required: true,
        pattern: undefined,
        minLength: 3,
        maxLength: 20,
        feedback: "Por favor, ingresa tu apellido.",
      },
    ],
  },
  {
    rowId: 2,
    cols: [
      {
        colId: 1,
        md: 8,
        name: "email",
        label: "Correo electrónico",
        type: "email",
        required: true,
        pattern: "^.+@.+\\.[a-zA-Z]{2,}$",
        minLength: 5,
        maxLength: 30,
        feedback: "Por favor, ingresa un correo electrónico válido.",
      },
      {
        colId: 2,
        md: 4,
        name: "phone",
        label: "Teléfono",
        type: "tel",
        required: true,
        pattern: "^3[0-9]{9}$",
        minLength: 10,
        maxLength: 10,
        feedback: "Por favor, ingresa un teléfono válido (ej: 3001234567).",
      },
    ],
  },
];
